# Welcome to Jekyll!
#

# Site settings
title: Pirátská strana | JIHOMORAVSKY KRAJ
description: > # this means to ignore newlines until "baseurl:"
  Česká pirátská strana - Jihomoravský kraj
keywords: piráti, česká pirátská strana, svoboda, demokracie, jihomoravský kraj, Brno, Brňenský
url: "https://jihomoravsky.pirati.cz" # the base hostname & protocol for your site



administrator:
    email: jana.leitnerova@pirati.cz, jan.suchanek@gmail.com # mail kam pujdou chybove vystupy

mediaStorage: jihomoravsky #obrazky a pdf jsou na https://a.pirati.cz/jihomoravsky/

emptyArray: []

organization:
  name: Pirátská strana | JIHOMORAVSKÝ
  shortName: Piráti JMK
  contactUid: vendula.svobodova
  email: vendula.svobodova@pirati.cz
  phone: +420 778 111 453
  address: |
      Pirate Space Brno
      Údolní 37 (suterén)
      60200 Brno
  residenceImg: miscellaneous/residence.png
  mapLink: https://www.google.com/maps/place/Denisova+639%2F2,+702+00+Moravsk%C3%A1+Ostrava+a+P%C5%99%C3%ADvoz/@49.8335046,18.2859436,17z/data=!3m1!4b1!4m5!3m4!1s0x4713e330b9662287:0x70f2934230719ddf!8m2!3d49.8335046!4d18.2881323?shorturl=1
  redmineLink: https://forum.pirati.cz/viewforum.php?f=735
  dataBoxId: b2i4r6j
  transparentAccount: 2100048174/2010

contactSummaryItems:
 - type: organizationEmail
 - type: organizationPhone
 - type: organizationRedmineLink
 - type: organizationDataBox
 - type: organizationTransparentAccount
 - type: piratiRootWebsite
   includeMoreLink: true
 - type: custom
   iconClass: fa fa-facebook
   label: Facebook
   body: <a href="https://www.facebook.com/CPS.JMK/">@CPS.JMK</a>
 - type: custom
   iconClass: fa fa-twitter
   label: Twitter
   body: <a href="https://twitter.com/PiratskaStrana">@PiratskaStrana</a>

video:
  # For nice look of the calendar, make sure you get Google Calendar API key
  # and start the app with the env var `GOOGLE_CALENDAR_APIKEY=[myapikey] bundle exec jekyll serve`.
  # For deployment, contact website administrator to set you env variable.
#  title: Krajský kalendář
#  id: nk73m1m89vhf5g2vojp6tnqe58@group.calendar.google.com
#  page: https://calendar.google.com/calendar/embed?showTitle=0&amp;showNav=0&amp;showDate=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0&amp;mode=AGENDA&amp;height=550&amp;wkst=2&amp;bgcolor=%23ffffff&amp;src=i7ipksvi9b852grgjic8mnhua0%40group.calendar.google.com&ctz=Europe%2FPrague

calendar:
  # For nice look of the calendar, make sure you get Google Calendar API key
  # and start the app with the env var `GOOGLE_CALENDAR_APIKEY=[myapikey] bundle exec jekyll serve`.
  # For deployment, contact website administrator to set you env variable.
  title: Krajský kalendář
  id: nk73m1m89vhf5g2vojp6tnqe58@group.calendar.google.com
  page: https://calendar.google.com/calendar/embed?src=aab301nnugmna65grbnt6jv18k%40group.calendar.google.com&ctz=Europe%2FPrague
facebook:
  loadSDK: true
  #vyplntě adresu vaší stranky, funguje pouze na stránky nikoliv skupiny
  profilePage: "https://www.facebook.com/cps.jmk/"

twitter:
  loadSDK: true
  profile: PiratskaStrana

instagram:
  profilePage: https://www.instagram.com/piratiJMK

flicker:
  profilePage: https://www.flickr.com/photos/pirati/

forum:
  page: https://forum.pirati.cz/jihomoravsky-kraj-f83/

github:
  url: https://github.com/pirati-web/jihomoravsky.pirati.cz/
  branch: master


###################technické

github_username:  pirati-web

sass:
  style: compressed
  sass_dir: _sass

theme: jekyll-theme-pirati

markdown: kramdown
theme: jekyll-theme-pirati
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-environment-variables
paginate_path: "/aktuality/:num/"
paginate: 11

exclude:
  - readme.md
  - Gemfile
  - Gemfile.lock
  - package.json
  - bower.json
  - gulpfile.js
  - node_modules
  - bower_components
  - vendor  

permalink: /aktuality/:title.html
collections:
  people:
    output: true
    permalink: /lide/:path/
  program:
    output: true
    permalink: /volby/:path/
  teams:
    output: true
    permalink: /pripoj-se/:title/
  candidatelists:
    output: false

defaults:   # defaults values for collection scope
  -
    scope:
      path: "_people"
    values:
      layout: "person"
      rbar: 
        - foto
        - personContact
        - personArticles
          #- people
  -
    scope:
      path: "_program"
    values:
      layout: "program-post"
      rbar: "volby"
      #- garant
      #   - program
  -
    scope:
      path: "_teams"
    values:
      layout: "team"
      rbar: "team-summary, teams-toc"
  -
    scope:
      path: "_posts"
    values:
      layout: "post"

fb: https://www.facebook.com/cpsmsk
tw: PiratiMSK

emptyArray: []

assets:
  source_maps: true
  compression: true
  gzip: false
  plugins:
    css: { autoprefixer: {}}
    img:
      optim:
        jpegoptim:
          strip: all
          max_quality: 80
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
  sources:
    - vendor/bundle/ruby/2.5.0/gems/jekyll-theme-pirati-7.7.1/_sass
    - assets/css
    - assets/fonts
    - assets/video
    - assets/img
    - assets/img/posts
    - assets/snippet
    - _sass
