version: '3'
services:
  site:
    #bash -c "bundle install --path vendor/bundle && bundle exec htmlproofer --assume-extension ./_site && bundle exec jekyll serve --watch --livereload --host 0.0.0.0"
    #bash -c "bundle install --path vendor/bundle && bundle exec jekyll serve --watch --livereload --host 0.0.0.0"
    command: >
        bash -c "bundle install --path vendor/bundle && bundle exec jekyll serve --watch --livereload --host 0.0.0.0"
    build: .
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000
      - 35729:35729
